### PR TITLE
Fix Javadoc warnings with Java 21

### LINKED ISSUE #77: Address javadoc warnings with Java 21+
Found in https://github.com/strimzi/metrics-reporter/pull/73#issuecomment-2742840542. When running with Java 21 we get some javadoc warnings:
```
[WARNING] Javadoc Warnings
[WARNING] /Users/mickael/github/metrics-reporter/client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/common/AbstractReporter.java:20: warning: use of default constructor, which does not provide a comment
[WARNING] public abstract class AbstractReporter {
[WARNING] ^
[WARNING] /Users/mickael/github/metrics-reporter/client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/common/DataPointSnapshotBuilder.java:20: warning: use of default constructor, which does not provide a comment
[WARNING] public class DataPointSnapshotBuilder {
[WARNING] ^
[WARNING] /Users/mickael/github/metrics-reporter/client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/http/HttpServers.java:20: warning: use of default constructor, which does not provide a comment
[WARNING] public class HttpServers {
[WARNING] ^
[WARNING] /Users/mickael/github/metrics-reporter/client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/http/Listener.java:76: warning: use of default constructor, which does not provide a comment
[WARNING] public static class ListenerValidator implements ConfigDef.Validator {
[WARNING] ^
[WARNING] 4 warnings
```

### PR DESCRIPTION
**Pull request by mimaison**
Fixes #77

### CODE REVIEW

File: client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/common/AbstractReporter.java [hunk 1]
```diff
@@ -27,6 +27,11 @@ public abstract class AbstractReporter {
     // allowlist is updated we can update the matching metrics.
     private final Map<Object, MetricWrapper> disallowedMetrics = new ConcurrentHashMap<>();
 
+    /**
+     * Empty constructor
+     */
+    public AbstractReporter() { }
```
Comment (see-quick) [inline client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/common/AbstractReporter.java:33]: Do we need to expose it? Can't we just use private or protected?
```suggestion
    public AbstractReporter() { }
```

**Review by see-quick — APPROVED** [review]
LGTM, just a nit.

**Review by ppatierno — APPROVED** [review]

File: client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/common/AbstractReporter.java (hunk 1 above)
Comment (mimaison) [reply client-metrics-reporter/src/main/java/io/strimzi/kafka/metrics/prometheus/common/AbstractReporter.java:33]: Yes it needs to be `public`, we have concrete implementations in other packages.
